apiVersion: mpas.ocm.software/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/instance: project-sample
    app.kubernetes.io/part-of: mpas-project-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mpas-project-controller
  name: project-sample
spec:
  # TODO(user): Add fields here
