---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mpas-projects-clusterrole
rules:
- apiGroups:
  - mpas.ocm.software
  resources:
  - subscriptions
  - targets
  verbs:
  - get
  - list
  - watch
