name: Check for diff after manifest and generated targets

on:
  pull_request: {}

jobs:
  check:
    name: Check for diff
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/open-component-model
    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.OCMBOT_APP_ID }}
        private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git config --global url.https://${{ secrets.OCMBOT_APP_ID }}:${{ steps.generate_token.outputs.token }}@github.com/.insteadOf https://github.com/
    - name: Make manifests && generate
      run: |
        make manifests && make generate
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: '${{ github.workspace }}/go.mod'
    - name: Restore Go cache
      uses: actions/cache@v3
      with:
        path: /home/runner/work/_temp/_github_home/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: go mod tidy
      run: |
        go mod tidy
    - name: Check for diff
      run: |
        git diff --exit-code --shortstat
